//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusyBookCard
    {
        public int Id { get; set; }
        public int ReaderId { get; set; }
        public System.DateTime BusyDateTimeBegin { get; set; }
        public System.DateTime BusyDateTimeEnd { get; set; }
    
        public virtual BookInstance BookInstance { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
