//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribtion
    {
        public int Id { get; set; }
        public System.DateTime DurationTimeBegin { get; set; }
        public System.DateTime DurationTimeEnd { get; set; }
        public DatabaseLibrary.Genres Genre { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
