//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInstance
    {
        public int Id { get; set; }
        public int DescriptionId { get; set; }
        public bool IsBusy { get; private set; }
    
        public virtual BookDescription BookDescription { get; set; }
        public virtual BusyBookCard BusyBookCard { get; set; }
    }
}
